### ISSUE TITLE
crash server

### ISSUE THREAD

**Issue by blakpsykozz** [codetaylor/artisan-worktables#229]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

*crash server*

If this issue occurs in a modpack, please report this to the modpack author. Also, please take the time to look at existing issues to ensure you don't create a duplicate. You may remove this line and place your issue description here.

*[/replace]*

#### What Happens

*[replace]*

* Describe what happens
* Describe, in detail, the steps required to reproduce the issue

*[/replace]*

#### What You Expect to Happen

*[replace]*

* Describe what you expect to happen

*[/replace]*

#### Script

*[replace]*

If your issue involves a CraftTweaker script, please place a **LINK** to your script here.

**DO NOT** paste your script here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Crash Log

*Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Artisan Automation (artisanautomation)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.getConstructor(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at com.codetaylor.mc.artisanautomation.modules.automator.ModuleAutomator.<init>(ModuleAutomator.java:113)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at com.codetaylor.mc.athenaeum.module.ModuleConstructor.constructModule(ModuleConstructor.java:13)
	at com.codetaylor.mc.athenaeum.module.ModuleRegistry.initializeModules(ModuleRegistry.java:34)
	at com.codetaylor.mc.athenaeum.module.ModuleManager.onConstructionEvent(ModuleManager.java:66)
	at com.codetaylor.mc.artisanautomation.ModArtisanAutomation.on(ModArtisanAutomation.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 52 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 54 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_231, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 965418152 bytes (920 MB) / 1381498880 bytes (1317 MB) up to 15271460864 bytes (14564 MB)
	JVM Flags: 2 total; -Xmx16G -XX:MaxPermSize=16384M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version       | Source                                  | Signature |
	|:----- |:------------------- |:------------- |:--------------------------------------- |:--------- |
	| LC    | minecraft           | 1.12.2        | minecraft.jar                           | None      |
	| LC    | mcp                 | 9.42          | minecraft.jar                           | None      |
	| LC    | FML                 | 8.0.99.99     | forge-1.12.2-14.23.5.2847-universal.jar | None      |
	| LC    | forge               | 14.23.5.2847  | forge-1.12.2-14.23.5.2847-universal.jar | None      |
	| LC    | crafttweaker        | 4.1.20        | CraftTweaker2-1.12-4.1.20.564.jar       | None      |
	| LC    | athenaeum           | 1.12.2-1.18.0 | athenaeum-1.12.2-1.18.0.jar             | None      |
	| LC    | artisanworktables   | 1.12.2-1.23.0 | artisanworktables-1.12.2-1.23.0.jar     | None      |
	| LE    | artisanautomation   | 1.12.2-1.0.1  | artisanautomation-1.12.2-1.0.1.jar      | None      |
	| L     | artisanintegrations | 1.12.2-1.2.1  | artisanintegrations-1.12.2-1.2.1.jar    | None      |
	| L     | crafttweakerjei     | 2.0.3         | CraftTweaker2-1.12-4.1.20.564.jar       | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)*

If your issue involves a crash log, please place a **LINK** to your crash log here.

**DO NOT** paste your crash log here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:1.12.2
* Forge:14.23.5.2847
* CraftTweaker:4.1.20.564
* Artisan Worktables:1.23.0
* Athenaeum:1.18.0

**Comment by codetaylor** [comment]
Thanks for the report!

In the future, please follow the template instructions regarding crash logs:

> If your issue involves a crash log, please place a LINK to your crash log here.
>
> DO NOT paste your crash log here. Please use a service such as pastebin, hastebin, or gist.

Fixed in version `1.0.2`

**Comment by blakpsykozz** [comment]
okay excuse me ^^

**Comment by blakpsykozz** [comment]
thanks for  this fixe

**Comment by codetaylor** [comment]
You're welcome :)
