### ISSUE TITLE
"ArtisanIngredient cannot be cast to CTArtisanIngredient" crash

### ISSUE THREAD

**Issue by copygirl** [codetaylor/artisan-worktables#240]
#### Issue Description

Game crashes when trying to fill a partially filled bucket of clay from Hardcore Bytes Mod with more clay.

Related: #238

#### Steps To Reproduce

- `/give @p pyrotech:bucket_wood`
- `/give @p clay_ball 64`
- Craft empty bucket with clay ball.
- Place partially filled bucket with clay ball into any AW worktable.

#### Script

[`bucket_of_clay.zs`](https://gist.github.com/copygirl/8546f214803db6c834a94911c908daaf)

#### Crash Log

Full crash report: [Here!](https://gist.github.com/copygirl/ac70fff8c74ce288f45bd30953d5dbb9)
```
java.lang.ClassCastException: com.codetaylor.mc.artisanworktables.api.internal.recipe.ArtisanIngredient cannot be cast to com.codetaylor.mc.artisanworktables.modules.worktables.integration.crafttweaker.CTArtisanIngredient
	at com.codetaylor.mc.artisanworktables.modules.worktables.integration.crafttweaker.CTArtisanRecipe.getMarksShapeless(CTArtisanRecipe.java:321)
	at com.codetaylor.mc.artisanworktables.modules.worktables.integration.crafttweaker.CTArtisanRecipe.processRecipeFunction(CTArtisanRecipe.java:217)
	at com.codetaylor.mc.artisanworktables.modules.worktables.integration.crafttweaker.CTArtisanRecipe.getBaseOutput(CTArtisanRecipe.java:94)
	at com.codetaylor.mc.artisanworktables.modules.worktables.gui.AWContainer.updateRecipeOutput(AWContainer.java:476)
	at com.codetaylor.mc.artisanworktables.modules.worktables.tile.spi.TileEntityBase.triggerContainerRecipeUpdate(TileEntityBase.java:202)
	at com.codetaylor.mc.artisanworktables.modules.worktables.tile.spi.TileEntityBase.func_189517_E_(TileEntityBase.java:441)
	at com.codetaylor.mc.artisanworktables.modules.worktables.tile.spi.TileEntityBase.func_189518_D_(TileEntityBase.java:428)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

#### Affected Versions / Used Mods

- Minecraft: 1.12.2
- Forge: 14.23.5.2854
- CraftTweaker: [4.1.20.576](https://media.forgecdn.net/files/2969/711/CraftTweaker2-1.12-4.1.20.576.jar)
- Artisan Worktables: [1.23.2](https://media.forgecdn.net/files/2964/269/artisanworktables-1.12.2-1.23.2.jar)
  - Athenaeum: [1.18.1](https://media.forgecdn.net/files/2964/268/athenaeum-1.12.2-1.18.1.jar)
- Pyrotech: [1.4.29](https://media.forgecdn.net/files/2967/734/pyrotech-1.12.2-1.4.29.jar)
  - Dropt: [1.18.0](https://media.forgecdn.net/files/2957/599/dropt-1.12.2-1.18.0.jar)
- Hardcore Bytes Mod: [0.1.0-SNAPSHOT+8da5861](https://meowface.org/copygirl/HardcoreBytesMod-1.12.2-0.1.0-SNAPSHOT+8da5861.jar)
  - Immersive Engineering: [92](https://media.forgecdn.net/files/2799/143/ImmersiveEngineering-0.12-92.jar)

**Comment by codetaylor** [comment]
Reproduced with:

```zs
recipes.addShapeless("test", <minecraft:diamond>,
    [ <minecraft:dirt>.marked("dirt"), <minecraft:clay_ball> ],
    function(out, ins, cInfo) { return ins.dirt; }, null);
```

* Only occurs when a recipe function exists with at least one `Ingredient`
* Confirmed mixture of `CTArtisanIngredient` and `ArtisanIngredient` is a normal occurrence for AW converted CrT recipes

Thanks for the thorough report!

Should be fixed in the next patch `1.23.3`
