### ISSUE TITLE
ArrayIndexOutOfBoundsException in c.c.m.artisanworktables.modules.worktables.gui.Container

### ISSUE THREAD

**Issue by Volune** [codetaylor/artisan-worktables#249]
## Current Behavior
Game crash in
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.codetaylor.mc.artisanworktables.modules.worktables.gui.Container.func_184996_a(Container.java:878)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at com.codetaylor.mc.athenaeum.gui.GuiContainerBase.func_146274_d(GuiContainerBase.java:69)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

## Steps to Reproduce (for bugs)
1. Open worktable GUI
2. Try to make a "3 in a row" recipe (like paper recipe) but start from the middle and go too far to the left.
    In other words: select a stack of items for the recipe, mouse over the center of the worktable, press button, drag mouse to the left until outside of the crafting grid. Game crash.

## Crash Log
https://gist.github.com/Volune/23f353926ed90f74771a14ae1ea9124e

## Your Environment
In modpack FTB Interactions v2.0.2

**Comment by codetaylor** [comment]
What versions of the relevant mods?

* Minecraft:
* Forge:
* CraftTweaker:
* Artisan Worktables:
* Artisan Automation:
* Artisan Integrations:
* Artisan Workstumps:
* Athenaeum:

**Comment by codetaylor** [comment]
Pretty sure this was fixed in `1.12.2-1.21.7`. See https://github.com/codetaylor/artisan-worktables-1.12/issues/177

**Comment by Volune** [comment]
Got it, sorry didn't find that issue before opening (I had a quick search from the exception name)

**Comment by codetaylor** [comment]
Yeah, no worries. :) It took me ten minutes to find it and I knew it was there...
