### ISSUE TITLE
Crashes "WeightedRandom"

### ISSUE THREAD

**Issue by Xaikii** [codetaylor/artisan-worktables#30]
https://pastebin.com/tqUMSCRM

occurs when being in a Worktable, no current idea when it happens, most-likely randomly when I don't move my mouse

Versions:
Artisans-Worktable 1.8.16
Athaenum 1.4.3
Forge 14.23.1.2599

**Comment by codetaylor** [comment]
As far as I can tell, this doesn't have anything to do with my mod. The stacktrace provided doesn't path through any of my code.

```
java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:18)
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:37)
	at net.minecraft.world.WorldServer.func_175734_a(WorldServer.java:246)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:127)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:203)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

It's all Minecraft code. I don't use WeightedRandom at all. I have my own [WeightedPicker](https://github.com/codetaylor/athenaeum/blob/master/src/main/java/com/codetaylor/mc/athenaeum/util/WeightedPicker.java).

**Comment by codetaylor** [comment]
Yep. I investigated further and this is definitely occurring because Minecraft is trying to spawn mobs from a biome's mob list and that list has a total spawn weight `<= 0`. I would say that the problem lies with a mod that adds biomes and/or mobs.

**Comment by TheQKnight** [comment]
did anyone figure this out? even though its probably not related to this mod, I am having the exact same crash.
